### ISSUE TITLE
Not creating the commit

### ISSUE THREAD

**Issue by jjzcru** [piotrzaborow/nova-conventional-commits#1]
I did the following steps:
1. Run `git add .`
2. Fill all the required and optional fields
3. Press enter

I run `git status` to see if someting changed and same as before running the command

https://user-images.githubusercontent.com/2231310/168640998-e3690815-fa00-404e-9a3c-32dc577fb952.mp4

**Comment by piotrzaborow** [comment]
Thanks for finding this bug. I will try to fix in next couple of days.

**Comment by jjzcru** [comment]
Any update in this bug?

**Comment by jjzcru** [comment]
?

**Comment by heyjaywilson** [comment]
Is there an update on this? I also ran into this bug.

**Comment by michalzadkowski** [comment]
@piotrzaborow 
This happens for me as well. I would really like to use this extension, as manually composing a commit message according to conventional commits rules is a bit daunting. Would you be able to fix it? Or is the extension abandoned?

**Comment by piotrzaborow** [comment]
Everyone, thanks for sharing. I was going to fix it, but I got backtracked with personal issues. 

I'll try to make the fix as fast as I can, so you'll be able to use.

Sorry for the inconvenience.

**Comment by piotrzaborow** [comment]
I've made a change & new version is already published. Please check it out.
